import type {
  Campsite,
  Collection,
  CollectionPlace,
  CommunitySubmission,
  FieldReport,
  Goal,
  Media,
  Place,
  Trip,
  TripStop,
  Visit,
} from "./types";

const now = "2026-08-15T12:00:00.000Z";

export const seedPlaces: Place[] = [
  {
    id: "place-delta-lake",
    slug: "delta-lake-state-park",
    name: "Delta Lake State Park",
    type: "state_park",
    latitude: 43.2758,
    longitude: -75.4142,
    county: "Oneida",
    region: "Central New York",
    personalStatus: "visited",
    managingAgency: "NYS Office of Parks, Recreation and Historic Preservation",
    officialWebsite: "https://parks.ny.gov/parks/93",
    officialSource: {
      type: "NYS_PARKS",
      sourceUrl: "https://parks.ny.gov/parks/93",
      official: true,
    },
    description:
      "A 400-acre park on the shore of Delta Reservoir with camping, a beach, boat launch, and fishing access near Rome.",
    accessInfo: "Main entrance off Rome-Taberg Road. Day-use and campground parking on site.",
    amenities: ["Campground", "Beach", "Boat launch", "Picnic areas", "Showers"],
    lastPersonallyVerified: "2026-08-15",
    coverImage: "/images/explore/card.jpg",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-letchworth",
    slug: "letchworth-state-park",
    name: "Letchworth State Park",
    type: "state_park",
    latitude: 42.587,
    longitude: -78.002,
    county: "Wyoming",
    region: "Western New York",
    personalStatus: "visited",
    managingAgency: "NYS Parks",
    officialWebsite: "https://parks.ny.gov/parks/79",
    officialSource: { type: "NYS_PARKS", official: true, sourceUrl: "https://parks.ny.gov/parks/79" },
    description: "The Grand Canyon of the East — three major waterfalls on the Genesee River.",
    lastPersonallyVerified: "2026-06-02",
    coverImage: "/images/explore/about.jpg",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-watkins-glen",
    slug: "watkins-glen-state-park",
    name: "Watkins Glen State Park",
    type: "state_park",
    latitude: 42.3764,
    longitude: -76.8733,
    county: "Schuyler",
    region: "Finger Lakes",
    personalStatus: "visited",
    managingAgency: "NYS Parks",
    officialWebsite: "https://parks.ny.gov/parks/142",
    officialSource: { type: "NYS_PARKS", official: true, sourceUrl: "https://parks.ny.gov/parks/142" },
    description: "A narrow gorge with 19 waterfalls along a stone staircase trail.",
    lastPersonallyVerified: "2025-10-12",
    coverImage: "/images/explore/recent-1.jpg",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-taughannock",
    slug: "taughannock-falls-state-park",
    name: "Taughannock Falls State Park",
    type: "state_park",
    latitude: 42.5356,
    longitude: -76.6114,
    county: "Tompkins",
    region: "Finger Lakes",
    personalStatus: "want_to_visit",
    managingAgency: "NYS Parks",
    officialWebsite: "https://parks.ny.gov/parks/126",
    officialSource: { type: "NYS_PARKS", official: true, sourceUrl: "https://parks.ny.gov/parks/126" },
    description: "A 215-foot waterfall that drops farther than Niagara, with rim and gorge trails.",
    coverImage: "/images/explore/card.jpg",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-green-lakes",
    slug: "green-lakes-state-park",
    name: "Green Lakes State Park",
    type: "state_park",
    latitude: 43.0492,
    longitude: -75.9661,
    county: "Onondaga",
    region: "Central New York",
    personalStatus: "visited",
    managingAgency: "NYS Parks",
    officialWebsite: "https://parks.ny.gov/parks/172",
    officialSource: { type: "NYS_PARKS", official: true, sourceUrl: "https://parks.ny.gov/parks/172" },
    description: "Two glacial meromictic lakes with a distinctive turquoise color, camping, and a beach.",
    lastPersonallyVerified: "2026-07-04",
    coverImage: "/images/explore/recent-1.jpg",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-niagara",
    slug: "niagara-falls-state-park",
    name: "Niagara Falls State Park",
    type: "state_park",
    latitude: 43.0868,
    longitude: -79.0669,
    county: "Niagara",
    region: "Western New York",
    personalStatus: "unvisited",
    managingAgency: "NYS Parks",
    officialWebsite: "https://parks.ny.gov/parks/46",
    officialSource: { type: "NYS_PARKS", official: true, sourceUrl: "https://parks.ny.gov/parks/46" },
    description: "The oldest state park in the U.S., overlooking the American Falls and Niagara Gorge.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-minnewaska",
    slug: "minnewaska-state-park-preserve",
    name: "Minnewaska State Park Preserve",
    type: "state_park",
    latitude: 41.7352,
    longitude: -74.2391,
    county: "Ulster",
    region: "Catskills / Hudson Valley",
    personalStatus: "want_to_visit",
    managingAgency: "NYS Parks",
    officialWebsite: "https://parks.ny.gov/parks/127",
    officialSource: { type: "NYS_PARKS", official: true, sourceUrl: "https://parks.ny.gov/parks/127" },
    description: "Sky lakes, white-cliff carriage roads, and waterfalls on the Shawangunk Ridge.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-azure-tower",
    slug: "azure-mountain-fire-tower",
    name: "Azure Mountain Fire Tower",
    type: "fire_tower",
    latitude: 44.5403,
    longitude: -74.5008,
    county: "Franklin",
    region: "Adirondacks",
    personalStatus: "visited",
    managingAgency: "NYS DEC",
    officialSource: { type: "NYS_DEC", official: true },
    description: "A restored 35-foot steel fire tower with a short, steep climb and wide Adirondack views.",
    lastPersonallyVerified: "2026-05-18",
    coverImage: "/images/explore/about.jpg",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-rondaxe-tower",
    slug: "bald-mountain-rondaxe-fire-tower",
    name: "Bald Mountain (Rondaxe) Fire Tower",
    type: "fire_tower",
    latitude: 43.7544,
    longitude: -74.9111,
    county: "Herkimer",
    region: "Adirondacks",
    personalStatus: "want_to_visit",
    managingAgency: "NYS DEC",
    officialSource: { type: "NYS_DEC", official: true },
    description: "A popular family hike near Old Forge with a restored fire tower over the Fulton Chain.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-marcy",
    slug: "mount-marcy",
    name: "Mount Marcy",
    type: "trail",
    latitude: 44.1128,
    longitude: -73.9235,
    county: "Essex",
    region: "Adirondacks",
    personalStatus: "want_to_visit",
    managingAgency: "NYS DEC",
    officialSource: { type: "NYS_DEC", official: true },
    description: "Highest peak in New York at 5,344 feet. Long approach from the Adirondack Loj.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-loj-parking",
    slug: "adirondack-loj-trailhead",
    name: "Adirondack Loj Trailhead",
    type: "trailhead",
    latitude: 44.1831,
    longitude: -73.9636,
    county: "Essex",
    region: "Adirondacks",
    personalStatus: "unvisited",
    managingAgency: "Adirondack Mountain Club / NYS DEC",
    description: "Primary High Peaks trailhead parking for Marcy, Algonquin, and Heart Lake.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-moose-river",
    slug: "moose-river-plains-primitive",
    name: "Moose River Plains Primitive Campsite",
    type: "primitive_campsite",
    latitude: 43.671,
    longitude: -74.672,
    county: "Hamilton",
    region: "Adirondacks",
    personalStatus: "visited",
    managingAgency: "NYS DEC",
    officialSource: { type: "NYS_DEC", official: true },
    description: "Roadside primitive sites along the Moose River Plains Wild Forest network.",
    lastPersonallyVerified: "2026-08-12",
    coverImage: "/images/explore/card.jpg",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-johns-brook-leanto",
    slug: "johns-brook-lean-to",
    name: "Johns Brook Lean-to",
    type: "lean_to",
    latitude: 44.148,
    longitude: -73.837,
    county: "Essex",
    region: "Adirondacks",
    personalStatus: "unvisited",
    managingAgency: "NYS DEC",
    officialSource: { type: "NYS_DEC", official: true },
    description: "A High Peaks lean-to along Johns Brook, used as a base for Marcy and neighboring peaks.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-delta-launch",
    slug: "delta-lake-boat-launch",
    name: "Delta Lake Boat Launch",
    type: "boat_launch",
    latitude: 43.2789,
    longitude: -75.4211,
    county: "Oneida",
    region: "Central New York",
    personalStatus: "visited",
    parentPlaceId: "place-delta-lake",
    managingAgency: "NYS Parks",
    description: "Hard-surface launch into Delta Reservoir from the state park.",
    lastPersonallyVerified: "2026-08-15",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-oneida-fishing",
    slug: "oneida-lake-fishing-access",
    name: "Oneida Lake Fishing Access (Sylvan Beach)",
    type: "fishing_access",
    latitude: 43.196,
    longitude: -75.726,
    county: "Oneida",
    region: "Central New York",
    personalStatus: "visited",
    managingAgency: "NYS DEC",
    officialSource: { type: "NYS_DEC", official: true },
    description: "Shore and launch access on the eastern end of Oneida Lake.",
    lastPersonallyVerified: "2026-07-19",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-chittenango",
    slug: "chittenango-falls-state-park",
    name: "Chittenango Falls State Park",
    type: "waterfall",
    latitude: 42.978,
    longitude: -75.841,
    county: "Madison",
    region: "Central New York",
    personalStatus: "visited",
    managingAgency: "NYS Parks",
    officialWebsite: "https://parks.ny.gov/parks/156",
    officialSource: { type: "NYS_PARKS", official: true, sourceUrl: "https://parks.ny.gov/parks/156" },
    description: "A 167-foot waterfall with a short gorge trail and picnic grounds.",
    lastPersonallyVerified: "2026-04-22",
    coverImage: "/images/explore/recent-1.jpg",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-fair-haven",
    slug: "fair-haven-beach-state-park",
    name: "Fair Haven Beach State Park",
    type: "beach",
    latitude: 43.327,
    longitude: -76.703,
    county: "Cayuga",
    region: "Finger Lakes / Lake Ontario",
    personalStatus: "want_to_visit",
    managingAgency: "NYS Parks",
    officialWebsite: "https://parks.ny.gov/parks/41",
    officialSource: { type: "NYS_PARKS", official: true, sourceUrl: "https://parks.ny.gov/parks/41" },
    description: "Sandy Lake Ontario shoreline, camping, and a sheltered pond for paddling.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-whiteface-view",
    slug: "whiteface-veterans-memorial-highway",
    name: "Whiteface Veterans Memorial Highway Overlook",
    type: "viewpoint",
    latitude: 44.3659,
    longitude: -73.9026,
    county: "Essex",
    region: "Adirondacks",
    personalStatus: "unvisited",
    managingAgency: "NYS Olympic Regional Development Authority",
    description: "High-elevation overlooks and a summit castle on Whiteface Mountain.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-saranac",
    slug: "lower-saranac-lake",
    name: "Lower Saranac Lake",
    type: "lake",
    latitude: 44.314,
    longitude: -74.17,
    county: "Franklin",
    region: "Adirondacks",
    personalStatus: "want_to_visit",
    managingAgency: "NYS DEC",
    officialSource: { type: "NYS_DEC", official: true },
    description: "Island camping and paddling on the Saranac chain.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-hinckley",
    slug: "hinckley-reservoir-hand-launch",
    name: "Hinckley Reservoir Hand Launch",
    type: "hand_launch",
    latitude: 43.312,
    longitude: -75.108,
    county: "Oneida",
    region: "Adirondack Foothills",
    personalStatus: "unvisited",
    managingAgency: "NYS DEC / NYC DEP",
    description: "Carry-in access to Hinckley Reservoir, a large drinking-water reservoir with recreation access.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-pixley",
    slug: "pixley-falls-state-park",
    name: "Pixley Falls State Park",
    type: "picnic_area",
    latitude: 43.403,
    longitude: -75.338,
    county: "Oneida",
    region: "Central New York",
    personalStatus: "visited",
    managingAgency: "NYS Parks",
    officialWebsite: "https://parks.ny.gov/parks/110",
    officialSource: { type: "NYS_PARKS", official: true, sourceUrl: "https://parks.ny.gov/parks/110" },
    description: "A 50-foot waterfall, picnic tables, and a short trail north of Rome.",
    lastPersonallyVerified: "2026-03-08",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "place-ferns-wildlife",
    slug: "montezuma-national-wildlife-refuge",
    name: "Montezuma National Wildlife Refuge",
    type: "wildlife",
    latitude: 42.975,
    longitude: -76.738,
    county: "Seneca",
    region: "Finger Lakes",
    personalStatus: "want_to_visit",
    managingAgency: "U.S. Fish & Wildlife Service",
    description: "A major migratory bird stopover at the north end of Cayuga Lake.",
    createdAt: now,
    updatedAt: now,
  },
];

export const seedVisits: Visit[] = [
  {
    id: "visit-delta-1",
    placeId: "place-delta-lake",
    date: "2025-09-18",
    notes: "First overnight in loop B. Quiet after 9pm.",
    weather: "Clear, 62°F",
    activities: ["Camping", "Photography"],
  },
  {
    id: "visit-delta-2",
    placeId: "place-delta-lake",
    date: "2026-08-15",
    notes: "Shot campsite photos and launched the kayak at sunrise.",
    weather: "Hazy sun, 78°F",
    activities: ["Camping", "Kayaking", "Photography"],
    tripId: "trip-cny-loop-2026",
    goalsCompleted: ["goal-delta-sunset"],
  },
  {
    id: "visit-letchworth-1",
    placeId: "place-letchworth",
    date: "2026-06-02",
    notes: "Inspiration Point at golden hour, then Upper Falls.",
    activities: ["Hiking", "Photography"],
  },
  {
    id: "visit-watkins-1",
    placeId: "place-watkins-glen",
    date: "2025-10-12",
    notes: "Gorge Trail after rain — mist in the stone corridors.",
    activities: ["Hiking", "Photography"],
  },
  {
    id: "visit-azure-1",
    placeId: "place-azure-tower",
    date: "2026-05-18",
    notes: "Cabin-sized summit. Tower cab open.",
    activities: ["Hiking", "Photography"],
    tripId: "trip-adirondack-2026",
    goalsCompleted: ["goal-azure-tower"],
  },
  {
    id: "visit-moose-1",
    placeId: "place-moose-river",
    date: "2026-08-12",
    notes: "Site 24. Gravel pad, close to the river.",
    activities: ["Camping"],
    tripId: "trip-adirondack-2026",
  },
  {
    id: "visit-green-1",
    placeId: "place-green-lakes",
    date: "2026-07-04",
    notes: "Swam Round Lake, photographed the color shift at dusk.",
    activities: ["Swimming", "Photography"],
  },
  {
    id: "visit-chittenango-1",
    placeId: "place-chittenango",
    date: "2026-04-22",
    notes: "Spring runoff. Trail wet but open.",
    activities: ["Hiking", "Photography"],
  },
  {
    id: "visit-pixley-1",
    placeId: "place-pixley",
    date: "2026-03-08",
    activities: ["Photography"],
  },
  {
    id: "visit-oneida-1",
    placeId: "place-oneida-fishing",
    date: "2026-07-19",
    notes: "Walleye evening bite near the channel.",
    activities: ["Fishing"],
  },
  {
    id: "visit-delta-launch-1",
    placeId: "place-delta-launch",
    date: "2026-08-15",
    tripId: "trip-cny-loop-2026",
    activities: ["Kayaking"],
  },
];

export const seedTrips: Trip[] = [
  {
    id: "trip-adirondack-2026",
    slug: "adirondack-loop-2026",
    title: "Adirondack Exploration Loop",
    startDate: "2026-08-10",
    endDate: "2026-08-14",
    description:
      "A short loop through the western High Peaks foothills — primitive camping, a fire tower, and scouting Marcy.",
    coverImage: "/images/explore/about.jpg",
    milesTraveled: 186,
    activities: ["Camping", "Hiking", "Photography"],
    highlights: ["Azure Mountain cab views", "River-side primitive site"],
  },
  {
    id: "trip-cny-loop-2026",
    slug: "cny-water-weekend-2026",
    title: "CNY Water Weekend",
    startDate: "2026-08-14",
    endDate: "2026-08-16",
    description: "Delta Lake overnight plus a fishing stop on Oneida Lake.",
    coverImage: "/images/explore/card.jpg",
    milesTraveled: 42,
    activities: ["Camping", "Kayaking", "Fishing", "Photography"],
    highlights: ["Sunrise on Delta Reservoir"],
  },
];

export const seedTripStops: TripStop[] = [
  { id: "stop-a1", tripId: "trip-adirondack-2026", placeId: "place-moose-river", order: 1, notes: "Base camp" },
  { id: "stop-a2", tripId: "trip-adirondack-2026", placeId: "place-azure-tower", order: 2, notes: "Morning hike" },
  { id: "stop-a3", tripId: "trip-adirondack-2026", placeId: "place-rondaxe-tower", order: 3, notes: "Scouted, did not climb" },
  { id: "stop-c1", tripId: "trip-cny-loop-2026", placeId: "place-delta-lake", order: 1 },
  { id: "stop-c2", tripId: "trip-cny-loop-2026", placeId: "place-delta-launch", order: 2 },
  { id: "stop-c3", tripId: "trip-cny-loop-2026", placeId: "place-oneida-fishing", order: 3 },
];

export const seedMedia: Media[] = [
  {
    id: "media-delta-cover",
    kind: "photo",
    url: "/images/explore/card.jpg",
    alt: "Open water and treeline at Delta Lake",
    caption: "Delta Reservoir from the day-use lawn",
    date: "2026-08-15",
    placeId: "place-delta-lake",
    visitId: "visit-delta-2",
    tripId: "trip-cny-loop-2026",
  },
  {
    id: "media-azure",
    kind: "photo",
    url: "/images/explore/about.jpg",
    alt: "View from Azure Mountain",
    caption: "Looking west from the tower cab",
    date: "2026-05-18",
    placeId: "place-azure-tower",
    visitId: "visit-azure-1",
    tripId: "trip-adirondack-2026",
  },
  {
    id: "media-watkins",
    kind: "photo",
    url: "/images/explore/recent-1.jpg",
    alt: "Gorge trail mist",
    caption: "After rain in Watkins Glen",
    date: "2025-10-12",
    placeId: "place-watkins-glen",
    visitId: "visit-watkins-1",
  },
  {
    id: "media-letchworth",
    kind: "photo",
    url: "/images/hero/hero.jpg",
    alt: "River gorge overlook",
    caption: "Genesee gorge light",
    date: "2026-06-02",
    placeId: "place-letchworth",
    visitId: "visit-letchworth-1",
  },
];

export const seedGoals: Goal[] = [
  {
    id: "goal-delta-sunset",
    title: "Photograph sunset over the reservoir",
    status: "completed",
    placeId: "place-delta-lake",
    completedAt: "2026-08-15",
  },
  {
    id: "goal-delta-sites",
    title: "Photograph every campsite in Loop B",
    status: "pending",
    placeId: "place-delta-lake",
  },
  {
    id: "goal-azure-tower",
    title: "Photograph the fire tower",
    status: "completed",
    placeId: "place-azure-tower",
    completedAt: "2026-05-18",
  },
  {
    id: "goal-marcy",
    title: "Hike the main trail to the summit",
    status: "pending",
    placeId: "place-marcy",
  },
  {
    id: "goal-trip-drone",
    title: "Fly drone where legally permitted",
    status: "pending",
    tripId: "trip-adirondack-2026",
  },
];

export const seedCollections: Collection[] = [
  {
    id: "col-ny-parks",
    slug: "ny-state-parks",
    title: "New York State Parks",
    description: "A long-term pass through the NYS Parks I actually want to stand in.",
  },
  {
    id: "col-fire-towers",
    slug: "adirondack-fire-towers",
    title: "Adirondack Fire Towers",
    description: "Restored cabs and the hikes that lead to them.",
  },
  {
    id: "col-camped",
    slug: "places-ive-camped",
    title: "Places I’ve Camped",
    description: "Nights on the ground — primitive and developed.",
  },
];

export const seedCollectionPlaces: CollectionPlace[] = [
  { collectionId: "col-ny-parks", placeId: "place-delta-lake" },
  { collectionId: "col-ny-parks", placeId: "place-letchworth" },
  { collectionId: "col-ny-parks", placeId: "place-watkins-glen" },
  { collectionId: "col-ny-parks", placeId: "place-taughannock" },
  { collectionId: "col-ny-parks", placeId: "place-green-lakes" },
  { collectionId: "col-ny-parks", placeId: "place-niagara" },
  { collectionId: "col-ny-parks", placeId: "place-minnewaska" },
  { collectionId: "col-ny-parks", placeId: "place-fair-haven" },
  { collectionId: "col-ny-parks", placeId: "place-chittenango" },
  { collectionId: "col-ny-parks", placeId: "place-pixley" },
  { collectionId: "col-fire-towers", placeId: "place-azure-tower" },
  { collectionId: "col-fire-towers", placeId: "place-rondaxe-tower" },
  { collectionId: "col-camped", placeId: "place-delta-lake" },
  { collectionId: "col-camped", placeId: "place-moose-river" },
];

export const seedFieldReports: FieldReport[] = [
  {
    placeId: "place-delta-lake",
    accessDifficulty: "Easy",
    roadCondition: "Paved park roads",
    walkFromParking: "Campsites are drive-up",
    siteCondition: "Well maintained",
    privacy: "Moderate — loop B is tighter",
    shade: "Mixed",
    groundCondition: "Mostly level gravel pads",
    waterNearby: "Spigots in loop; reservoir for recreation",
    cellService: "Good Verizon",
    tentSuitability: "Excellent",
    rvSuitability: "Good, some shorter driveways",
    fishingNotes: "Panfish and bass from shore near the launch.",
    photographyNotes: "Best light is west-facing water at sunset.",
    overallRating: 4,
    personalNotes: "Quiet after check-in rush. Beach gets busy on weekends.",
  },
  {
    placeId: "place-moose-river",
    accessDifficulty: "Moderate",
    roadCondition: "Long dirt road, passable in a car when dry",
    walkFromParking: "Site 24 is roadside",
    privacy: "High",
    shade: "Mostly shaded",
    waterNearby: "River 40 yards",
    cellService: "None",
    tentSuitability: "Good",
    rvSuitability: "Not recommended",
    overallRating: 5,
    personalNotes: "Bring water. Beautiful at night.",
  },
];

export const seedCampsites: Campsite[] = [
  {
    id: "site-delta-b-001",
    placeId: "place-delta-lake",
    loop: "B",
    number: "001",
    siteType: "Standard",
    tentSuitable: true,
    rvSuitable: true,
    privacy: "Low",
    shade: "Partial",
    electric: true,
    waterfront: false,
    notes: "Near restroom. Shorter driveway.",
    photos: ["/images/explore/card.jpg"],
  },
  {
    id: "site-delta-b-002",
    placeId: "place-delta-lake",
    loop: "B",
    number: "002",
    siteType: "Standard",
    tentSuitable: true,
    rvSuitable: false,
    privacy: "Moderate",
    shade: "Heavy",
    electric: false,
    waterfront: false,
    notes: "Best tent pad in the loop so far.",
  },
  {
    id: "site-delta-b-014",
    placeId: "place-delta-lake",
    loop: "B",
    number: "014",
    siteType: "Premium",
    tentSuitable: true,
    rvSuitable: true,
    privacy: "High",
    shade: "Mixed",
    electric: true,
    waterfront: true,
    notes: "Water view through the trees. Book early.",
    photos: ["/images/explore/recent-1.jpg"],
  },
];

export const seedCommunity: CommunitySubmission[] = [
  {
    id: "comm-1",
    placeId: "place-delta-lake",
    username: "trailnote",
    submittedAt: "2026-08-18T14:12:00.000Z",
    visitDate: "2026-08-17",
    kind: "condition",
    body: "Loop B restroom was closed for cleaning around 2pm. Water spigot by site 8 working.",
    status: "pending",
  },
];
